### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by vahidalvandi** [asseco-voice/laravel-custom-fields#55]
where is documents ?

**Comment by Norgul** [comment]
The documentation you mean? I will finish it within the next few days, thanks.

**Comment by vahidalvandi** [comment]
i saw one column **form_id**  i want a sample integrate from generated with this form builder 
https://formbuilder.online/

**Comment by Norgul** [comment]
Package is primarily custom-field oriented. Form is just an additional table we're using with form.io integration, however the implementation logic is not a part of the package.

**Comment by Norgul** [comment]
https://github.com/asseco-voice/laravel-custom-fields/pull/56
