### ISSUE TITLE
Migration issue using MSSQL 

### ISSUE THREAD

**Issue by bvcmxy** [asseco-voice/laravel-custom-fields#70]
I'm using MsSQL and on the migrate step I have:

SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Introducing FOREIGN KEY constraint 'custom_field_relations_child_id_foreign' on table 'custom_field_relations' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints. (SQL: alter table "custom_field_relations" add constraint "custom_field_relations_child_id_foreign" foreign key ("child_id") references "custom_fields" ("id") on delete cascade)

Thank you

**Comment by Norgul** [comment]
Hello @bvcmxy 

could you try out `mssql_fix` branch and see if the fix works for you?

Thanks

**Comment by bvcmxy** [comment]
Working fine.

**Comment by Norgul** [comment]
@bvcmxy merged with `master` and published a new patch version. Enjoy
