### ISSUE TITLE
Migration Errors

### ISSUE THREAD

**Issue by shepherdscribe** [asseco-voice/laravel-custom-fields#84]
Env: Mac
Laravel 9

<img width="1113" alt="Screen Shot 2022-12-07 at 12 57 19 PM" src="https://user-images.githubusercontent.com/62448059/206092295-d2937f66-6b48-456c-b37b-36b6942756f0.png">

Hi, having errors on migrations when CustomFieldPackageSeeder in included in DatabaseSeeder.

<img width="846" alt="Screen Shot 2022-12-07 at 12 58 54 PM" src="https://user-images.githubusercontent.com/62448059/206092446-90d2d133-f946-4791-afa1-c3ef0908d59c.png">

**Comment by eskayamadeus** [comment]
Why has this been closed? I am literally having the same issue almost a year later.
